service: serverless-lambda-boilerplate
provider:
  name: aws
  runtime: nodejs4.3
  stage: %branch%
  region: eu-west-1
  iamRoleStatements:
      -  Effect: "Allow"
         Action:
           - "s3:ListBucket"
           - "s3:PutObject"
           - "s3:GetObject"
         Resource: arn:aws:s3:::*

functions:
  usersGet:
    handler: userHandler.users
    events:
      - http:
          path: users
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false
  userGet:
    handler: userHandler.user
    events:
      - http:
          path: user
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false

  userCreate:
    handler: userHandler.create
    events:
      - http:
          path: user
          method: post
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false
  userUpdate:
    handler: userHandler.update
    events:
      - http:
          path: user
          method: put
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false
  userDelete:
    handler: userHandler.delete
    events:
      - http:
          path: user
          method: delete
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false